name: Build & Test
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
      - uses: actions/checkout@v2 # Checkout the code from the repository

      - name: Use Node.js 18 # Use Node.js version 14
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run tsc

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: ./deploy.yml
