name: Build & Test
on:
  push:
    branches:
      - dev
  pull_request:

jobs:
  review:
    name: Chat GPT Code Peer Review
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - uses: actions/checkout@v3
      - uses: edelauna/gpt-review@v1
        with:
          openai_api_key: ${{ secrets.OPENAI_API_KEY }}
          ignore_files: package-lock.json

  build:
    name: Build & Test
    runs-on: ubuntu-latest # Use the latest version of Ubuntu

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run tsc

      - name: Run tests
        run: npm test

  deploy:
    needs: build
    name: Deploy
    if: github.ref == 'refs/heads/dev'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
