name: Deploy

on:
  workflow_call:
    secrets:
      TOKEN:
        description: Discord Api Token
        required: true
      CLIENT_ID:
        description: Discord Client Id
        required: true
      GUILD_ID:
        description: Discord server id (to be removed)
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: Main
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Deploy commands
        env:
          TOKEN: ${{ secrets.TOKEN }}
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          GUILD_ID: ${{ secrets.GUILD_ID }}
        run: npm run deploy-commands
